#!/usr/bin/env bash

PACKAGE_MANAGER=$1
PROJECT_PATH=$2
DIRECTORY_PATH=$3

SCRIPT_PATH=$(dirname "$0")

docker run --rm \
  -e PACKAGE_MANAGER="$PACKAGE_MANAGER"\
  -e PROJECT_PATH="$PROJECT_PATH"\
  -e DIRECTORY_PATH="$DIRECTORY_PATH"\
  -e GITHUB_ENTERPRISE_HOSTNAME="${GITHUB_HOST}"\
  -e GITHUB_ENTERPRISE_ACCESS_TOKEN="${GITHUB_TOKEN}"\
  -e CONTACT_NEXUS_USER_TOKEN="${CONTACT_NEXUS_CREDENTIALS}"\
  dependabot-script

#  -e CONTACT_NEXUS_USER_TOKEN_USERNAME="${CONTACT_NEXUS_USER_TOKEN_USERNAME}"\
#  -e CONTACT_NEXUS_USER_TOKEN_PASSWORD="${CONTACT_NEXUS_USER_TOKEN_PASSWORD}"\

# GITHUB_ACCESS_TOKEN -- github.com

#  -e GITHUB_PUBLIC_ACCESS_TOKEN="${GITHUB_PUBLIC_ACCESS_TOKEN}"\
#CONTACT_NEXUS_CREDENTIALS_USR
